version: '3'
services:
  db_app:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@NcRfUjX"
    networks:
      - fast-api-net
    ports:
      - "5432:5432"
  app:
    build: .
    restart: always    
    environment:      
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@NcRfUjX"
      POSTGRES_SERVER: db_app
    command: ["sh", "entrypoint.sh"]
    depends_on:
      - db_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    networks:
      - fast-api-net

networks:
  fast-api-net:
    driver: bridge